version: 0.2

env:
  git-credential-helper: yes
  variables:
    PYPI: testpypi
    PIP_FLAGS: --disable-pip-version-check --quiet --no-warn-conflicts

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - npm install -g aws-cdk
      - pip install ${PIP_FLAGS} --upgrade pip aws-sam-cli awscli
      - TAG=$(git name-rev --name-only HEAD | cut -d/ -f2)
  pre_build:
    commands:
      - pip install ${PIP_FLAGS} .[cicd]
  build:
    commands:
      - |
        if [ "$TAG" != "master" ]; then
          python3 setup.py sdist bdist_wheel
        fi
    finally:
      - echo Build done for ${TAG}
  post_build:
    commands:
      - |
        cat << EOF > ~/.pypirc
        [${PYPI}]
        username = __token__
        password = ${PYPI_TOKEN}
        EOF
        if [ "$TAG" != "master" ]; then
          echo Releasing aviv-cdk@${TAG}
          pip install ${PIP_FLAGS} twine;
          python3 -m twine upload --repository ${PYPI} dist/*
        fi

artifacts:
  files:
    - '**/*'
  base-directory: cdk.out/
  discard-paths: no

cache:
  paths:
    - '/root/.cache/**/*'