version: 0.2

# env:
#   variables:
#     AWS_REGION: eu-west-1

phases:
  install:
    runtime-versions:
      python: 3.x
  #   commands:
  #     - echo Entered the install phase...
  #     - apt-get update -y
  #     - apt-get install -y python-pip
  #   finally:
  #     - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - TAG=$(git name-rev --name-only HEAD | cut -d/ -f2)
      - |
        if [ "$TAG" != "master" ]; then
          pip install --quiet twine;
        fi
  build:
    commands:
      - pip install --quiet -r lambdas/cfn_resources/requirements.txt -t layers/cfn_resources/
      - |
        if [ "$TAG" != "master" ]; then
          python3 setup.py sdist bdist_wheel
        fi
    finally:
      - echo Build done for ${TAG}
  post_build:
    commands:
      - |
        cat << EOF > ~/.pypirc
        [testpypi]
        username = __token__
        password = ${PYPI_TOKEN}
        EOF
      - |
        if [ "$TAG" != "master" ]; then
          echo Releasing aviv-cdk@${TAG}
          python3 -m twine upload --repository testpypi dist/*
        fi

artifacts:
  files:
    - 'aviv_cdk/**/*'
    - '*'
  discard-paths: no
  secondary-artifacts:
    cfn_resources:
      files:
        - '**/*'
      name: cfn_resources-$(date +%Y-%m-%d)
      base-directory: layers/cfn_resources/
      discard-paths: no

cache:
  paths:
    - '/root/.cache/**/*'