version: 0.2

env:
  variables:
    AWS_REGION: eu-west-1
    PYPI_TOKEN: pypi-AgENdGVzdC5weXBpLm9yZwIkMjRmMTMzZDktNjZhMS00NTljLWIwN2MtZjRiY2E2YjEwOTk1AAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCxK0JvjQNzP3X8gJRUcgN4KIcHjJoZX7OM1ViPpv_hIA
  # parameter-store:

phases:
  # install:
  #   commands:
  #     - echo Entered the install phase...
  #     - apt-get update -y
  #     - apt-get install -y python-pip
  #   finally:
  #     - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - pip install --quiet twine
      - pip install --quiet -r lambdas/cfn_resources/requirements.txt -t layers/cfn_resources/
  build:
    commands:
      - python3 setup.py sdist bdist_wheel
    finally:
      - ls -la dist/
      - echo Build done!
  post_build:
    commands:
      - |
        cat << EOF > ~/.pypirc
        [testpypi]
        username = __token__
        password = ${PYPI_TOKEN}
        EOF
      - cat ~/.pypirc
      - python3 -m twine upload --repository testpypi dist/*

artifacts:
  files:
    - 'aviv_cdk/**/*'
    - '*'
  discard-paths: no
  secondary-artifacts:
    cfn_resources:
      files:
        - '**/*'
      name: cfn_resources-$(date +%Y-%m-%d)
      base-directory: layers/cfn_resources/
      discard-paths: no

cache:
  paths:
    - '/root/.cache/**/*'